### ISSUE TITLE
Use case Glossary:  YAML files , Plone protect  adjustments

### ISSUE THREAD

**Issue by fmacias64** [collective/rapido.plone#12]
Hi,
I have to modify the files .yaml of the **glossary use case**  for the use case to work in my plone installation
The error was:
```
2016-10-02 01:05:37 ERROR Zope.SiteErrorLog 1475388337.320.659587622434 http://localhost:8080/Plone/@@rapido/glossary/block/term
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module rapido.plone.browser.views, line 133, in __call__
  Module rapido.plone.browser.views, line 62, in content
  Module rapido.core.display, line 30, in GET
  Module rapido.core.app, line 102, in get_block
  Module rapido.core.block, line 82, in __init__
AttributeError: 'str' object has no attribute 'get'
```

In **term.yaml**

Changed from 

```
target: ajax
elements:
    term: TEXT
    definition: TEXT
   . . .
```

To:

```
target: ajax
elements:
    term: 
        type: TEXT
    definition:
        type: TEXT
 . . .
```

and in **all.yaml**

Changed from:

```
target: ajax
elements:
    list: BASIC
    new_term:
        type: ACTION
        label: Add term
```
To:
```
target:  ajax
elements:
    list: 
       type: BASIC
    new_term:
       type: ACTION
       label: Add term
```

Also in order to avoid plone.protect to block the app (through @@confirm-action), i have to  add one record directly on:

[http://localhost:8080/Plone/@@rapido/glossary/block/term](http://localhost:8080/Plone/@@rapido/glossary/block/term)

Greetings
