### ISSUE TITLE
ScannerError: mapping values are not allowed here into the source code from rapido.plone tutorial

### ISSUE THREAD

**Issue by macagua** [collective/rapido.plone#25]
I have a **"ScannerError: mapping values are not allowed here"** into the source code from [rapido.plone tutorial](http://rapidoplone.readthedocs.io/en/latest/tutorial.html#listing-the-top-5-items) at `rate.yaml` file.

My Plone settings:

*    Plone 5.0.7 (5017)
*    CMF 2.2.10
*    Zope 2.13.26
*    Python 2.7.3 (default, Jun 20 2016, 16:18:47) [GCC 4.7.2]
*    PIL 3.4.2 (Pillow)

```sh 
2017-04-04 19:00:05 ERROR Zope.SiteErrorLog 1491346805.170.857265025547 http://localhost:8080/Plone/++theme++my-rapido-theme/@@plone.resourceeditor.filemanager-actions
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.resourceeditor.browser, line 411, in __call__
  Module plone.resourceeditor.browser, line 203, in saveFile
  Module plone.resource.directory, line 171, in writeFile
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module rapido.plone.handlers, line 49, in resource_created_or_modified
  Module rapido.plone.handlers, line 27, in process_yaml
  Module yaml, line 71, in load
  Module yaml.constructor, line 37, in get_single_data
  Module yaml.composer, line 36, in get_single_node
  Module yaml.composer, line 55, in compose_document
  Module yaml.composer, line 84, in compose_node
  Module yaml.composer, line 127, in compose_mapping_node
  Module yaml.parser, line 98, in check_event
  Module yaml.parser, line 428, in parse_block_mapping_key
  Module yaml.scanner, line 116, in check_token
  Module yaml.scanner, line 220, in fetch_more_tokens
  Module yaml.scanner, line 576, in fetch_value
ScannerError: mapping values are not allowed here
  in "<string>", line 2, column 13:
        elements:
                ^
```

The problem is the tab indents at  at `rate.yaml` file.
```yaml
target: ajax
    elements:
        like:
            type: ACTION
            label: Like
        display: BASIC
        total:
            type: NUMBER
            index_type: field
```

Then, the solution is fixed the tab indents like this:
```yaml
target: ajax
elements:
    like:
        type: ACTION
        label: Like
    display: BASIC
    total:
        type: NUMBER
        index_type: field
```
