### ISSUE TITLE
extra view ONLY works if it matches the rapido app block name

### ISSUE THREAD

**Issue by pigeonflight** [collective/rapido.plone#34]
I wanted to map my rapido app to a custom extra view with an id of my choice. I followed this guide http://rapidoplone.readthedocs.io/en/latest/reference/display.html?highlight=view#extra-views1

# Steps to repeat

Create a rapido app with the following layout:

```
rapido/app/blocks/frontlinks.pt
rapdo/app/blocks/frontlinks.py
rapido/app/blocks/frontlinks.yaml

```
Define an extra view In the `frontlinks.yaml` file.

## If the view name matches the rapido app block name, it works
This works:
```
elements:
    links: 
        type: BASIC
view:
    id: frontlinks
    with_theme: true

```
I'm able to visit `@@frontlinks`.

## If the view name does not match the rapido app block name, it fails
This does not work:

```
elements:
    links: 
        type: BASIC
view:
    id: my-links
    with_theme: true
```
I'm unable to successfully access `@@my-links` instead I get a page not found type error.
